### PR TITLE
Test added 

### PR DESCRIPTION
**Pull request by c4ist**
added necessary stuff for test, if you need more specific instructions LMK

### CODE REVIEW

**Comment by cainsalcido** [comment]
files arent in the right spots.. sorry 😅

**Comment by IntegerAlex** [comment]
Now it somehow looks fine.

**Comment by IntegerAlex** [comment]
Attach test samples , Preferably images

**Comment by IntegerAlex** [comment]
@cainsalcido  I have added the test Structure in test directory check it and add your integrations

**Pull request closed without merging**
