### PR TITLE
changes to response.js and (hopefully) added the test 

### PR DESCRIPTION
**Pull request by cainsalcido**
(if it sucks sorry, relatively new, thought this would be fun to help with)

removed duplicate code (duplicate imports and function definitions.)
incorrect patch implementation (just fixed it to match PATCH the standard http method)
the `hasty` class constructor should have a `context` parameter to match the `Server` class constructor.

### CODE REVIEW

**Comment by IntegerAlex** [comment]
Appreciate it man.
My whole point to create this project was to understand and implement HTTP by myself somehow i turned it into a Framework, Anyways.
I will test it, and merge it .

**Comment by IntegerAlex** [comment]
Can you help us with [testing](https://github.com/IntegerAlex/hasty-server/discussions/19)

**Comment by cainsalcido** [comment]
not at the moment, finishing up class right now, i can try when i get home, if you're having issues with the testing it probably doesnt work anyways

**Comment by cainsalcido** [comment]
sorry :P

**Comment by IntegerAlex** [comment]
It has some issues, I think you verified from LLM .
I got what you did but there are some fixes i'll work on them don't get demotivated.

**Comment by cainsalcido** [comment]
Thanks for the feedback!! I'll keep looking for stuff to potentially add and fix, thanks.

**Comment by cainsalcido** [comment]
pretty sure i added the test (let me know if you need more specific parameters seemed kinda vague)

**Pull request closed without merging**
