### PR TITLE
[BUG #34 ] Hasty Server Logo is fixed

### PR DESCRIPTION
**Pull request by Amarjeetkumart**
#### The Hasty Server logo issue has been resolved. The incorrect file path that prevented the logo from displaying has been updated to point to the correct directory. As a result, the logo is now properly loading on the website, restoring the server's visual identity. Additionally, the site title has been updated to accurately reflect the server’s name, ensuring consistent branding across the platform.

### CODE REVIEW

**Comment by IntegerAlex** [comment]
Screenshot 2024-10-05 030057
In latest preview it still not showing

**Comment by IntegerAlex** [comment]
I fixed It

**Comment by IntegerAlex** [comment]
Please check issue  #35  and solve it

**Comment by IntegerAlex** [comment]
@Amarjeetkumart  Please test docs if you find other issue please report it

**Comment by Amarjeetkumart** [comment]
Thanks for fixing it, please Assign issue #35 to me i would like to work on it.

**Pull request closed without merging**
