### PR TITLE
feature/http-req-res 

### PR DESCRIPTION
**Pull request by mahabubx7**
### 🔨 feature/http-req-res

I have updated `server/index.js` and `server/response.js`. Refactored `Response` class-methods to avoid the header-definition conflicts for `json()` and `send()` .

issue: #11 

Now we can have the seven major HTTP methods:
- GET
- POST
- PUT *(newly added)*
- PATCH *(newly added)*
- DELETE *(newly added)*
- HEAD *(newly added)*
- OPTIONS *(newly added)* 

Also, can send json response in a express-js like chained way:
```js
server.get("/", (req,res)=>{
    console.log(req)
    res.status(200).json({status:200}) // new-way
})

server.post("/", (req,res)=>{
    console.log(req)
    res.status(201).json({status:201}) // new-way
})
```
Their sample response screenshots:
Screenshot at 23-02-50
Screenshot at 23-03-18

Hope you (@IntegerAlex) liked it 👍🏼 
~/mahabubx7

### CODE REVIEW

**Comment by IntegerAlex** [comment]
Let me check because other contributer also added some changes

**Comment by IntegerAlex** [comment]
Pull recent changes and make changes.

**Comment by mahabubx7** [comment]
> Pull recent changes and make changes.

✅ Done

**Comment by IntegerAlex** [comment]
Check new issue i am merging this.

**Comment by IntegerAlex** [comment]
Isssue #16

**Comment by IntegerAlex** [comment]
can you provide change log for this PR i will add to CHANGELOG.md

**Comment by IntegerAlex** [comment]
@mahabubx7

**Pull request merged**
