### PR TITLE
Need for Navigation buttons complete [fixed #33]

### LINKED ISSUE #33: Help : Needed for Navigation ( React Dev ).
Screenshot 2024-10-03 171406

Need this type of component to navigate between previous and next file for smooth flow.

### PR DESCRIPTION
**Pull request by Amarjeetkumart**
### Needed for Navigation ( React Dev ). #33  is now resolved

Screenshot from 2024-10-05 15-24-42

### CODE REVIEW

**Comment by IntegerAlex** [comment]
Its awesome. Can you add Name of next file after forward and previous file name on back . and focus should be on top after click

**Comment by Amarjeetkumart** [comment]
#### okay, may be i can do it gave me some time...

**Comment by IntegerAlex** [comment]
Yes take your time

**Comment by Amarjeetkumart** [comment]
#### check it Now..

**Comment by IntegerAlex** [comment]
Thankyou for your Genuine Contribution, You are good at your work

**Comment by IntegerAlex** [comment]
Add me on linkedIn

**Comment by Amarjeetkumart** [comment]
Thanks, i have added you on LinkedIn.

**Pull request merged**
