### PR TITLE
Added MIME-type lookup and sendFile() method to response Object

### PR DESCRIPTION
**Pull request by IntegerAlex**
#44  Added sendFIle() Will publish to Npm after through testing with version 0.6*

### CODE REVIEW

**Comment by IntegerAlex** [comment]
anything that could be Fixed ?

**Comment by mahabubx7** [comment]
> anything that could be Fixed ?

Looks good to me!
But, I would like to add more mime-types in the `mime-db` you have made.
For more specific data-type supports.

**Comment by IntegerAlex** [comment]
Yes add I know only these Types and see if any error handling is needed

**Comment by IntegerAlex** [comment]
> > anything that could be Fixed ?
> 
> Looks good to me! But, I would like to add more mime-types in the `mime-db` you have made. For more specific data-type supports.

Yes add I know only these Types and see if any error handling is needed

**Pull request merged**
