### PR TITLE
added basic doc for hasty server

### PR DESCRIPTION
**Pull request by prince-63**
Basic Docs Website Created!

Screenshot 2024-09-30 100756

### CODE REVIEW

**Comment by IntegerAlex** [comment]
Checked It Looks file,
Make it Black and i guess yellow (#f3ce1f) for anchor & hyperlink.
Till evening i will provide you more Details. 
I am not merging it now.

**Comment by prince-63** [comment]
ok

**Comment by IntegerAlex** [comment]
Bro made any progress?

**Comment by prince-63** [comment]
Yes bro I did.

**Comment by prince-63** [comment]
I change modified the website you can now.

**Comment by IntegerAlex** [comment]
Good Job I am Merging it, Please improve it further i am making some changes in doc.
Please pull and then make changes.

please write a doc file how to edit docs a Standardization so that anyone who wants to contribute can do contribute without breaking.

**Comment by prince-63** [comment]
I will add mdx for better documentation.

**Pull request merged**
